### ISSUE TITLE
Registered templates not appearing in Web UI

### ISSUE THREAD

**Issue by bmanturner** [blip-solutions/promptwatch-client#7] opened 2023-05-23 14:17 UTC
```
with PromptWatch(
    api_key="xxxxxxxxx"
) as pw:
    pw.register_prompt_template(name, prompt_template, "1.0")
```

I registered all the templates I use in my langchain project, and then ran the chains that use them multiple times. The sessions appear in the Web UI but the templates do not.

Langchain v0.0.176
Python 3.10.1

**Comment by ju-bezdek** [comment] 2023-05-23 20:48
@bmanturner I think that I've found the issue 
promptwatch client `0.1.2` was just released. Please update and let me know if it worked.

I'm pretty sure that the template will be recognized now, but since you seem not to be using native LLMChain from langchain (please confirm), you need to at least inherit from this class for your deepest chain (the one that is formating prompt template and calling the LLM). 

If there is a reason why you cant/dont want to do that, please let me know. I'd try to think about whether there is a way how to support your case.

That said, you should still be able to use 95% of PromptWatch features, but might be missing some of the best ones:)

You can verify that everything is working as it should if you WON'T see this info message in the prompt log detail
![image](https://github.com/blip-solutions/promptwatch-client/assets/27913091/fa338f79-ff75-4bd4-b546-4dd26b247030)

**Comment by bmanturner** [comment] 2023-05-23 21:03
That is correct I was subclassing LLMChain. I will verify this works as expected tomorrow and will report back. Thanks!

**Comment by bmanturner** [comment] 2023-05-24 13:13
The prompts are properly appearing in the UI, however I do receive warnings in the console now. I did not see these before updating promptwatch to 0.1.2 and I made no other changes.

```
WARNING:root:Error in on_chain_start callback: isinstance() arg 2 must be a type, a tuple of types, or a union

WARNING:root:Error in on_chain_end callback: 'NoneType' object has no attribute 'outputs'
```

**Comment by bmanturner** [comment] 2023-05-24 13:19
(sidenote: your [docs page](https://docs.promptwatch.com/) seems to be down)

**Comment by ju-bezdek** [comment] 2023-05-24 13:23
the domain is wrong ... it's docs.promptwatch**.io** not  docs.promptwatch**.com**

did you find that link somewhere, or did you just type that in?

**Comment by bmanturner** [comment] 2023-05-24 13:37
![CleanShot 2023-05-24 at 08 36 43@2x](https://github.com/blip-solutions/promptwatch-client/assets/8716214/bc9484d7-d38d-4300-9e3d-e951393613f2)

**Comment by ju-bezdek** [comment] 2023-05-24 13:40
These warnings are really weird...  I assume that since you have overridden the native LLMChain, you've also overridden some of the native methods and possibly you are not implementing the callbacks the way how standard langchain classes are...

The first error is an indicator of this... but it shouldn't happen anyways...
the latter is just a result of not expecting the first one

I've released an RC version to test pypi 
'pip install -i https://test.pypi.org/simple/ promptwatch==0.1.3rc1'

would you mind trying it out? It probably wont fix it, but might reveal the cause...

**Comment by ju-bezdek** [comment] 2023-05-24 13:49
great... and did it also create a correct session trace?

Fixed the link to the docs BTW...

**Comment by bmanturner** [comment] 2023-05-24 13:52
It certainly did. Thank you very much for the __prompt__ (hehe) attention to this. I think you have a very promising project here and I'm looking forward to trying out the unit tests next.

<img width="582" alt="CleanShot 2023-05-24 at 08 50 42@2x" src="https://github.com/blip-solutions/promptwatch-client/assets/8716214/51680363-633b-43ed-9233-7775f174b82e">

**Comment by ju-bezdek** [comment] 2023-05-24 13:55
Awesome 🎉

thanks for the feedback 🙏

Im going to test it once more with the  code snippet of your changes to double-check it, and then I'll release an official version

**Comment by ju-bezdek** [comment] 2023-05-24 14:06
FYI... your code seems to be fine, just my tests didn't cover that scenario...😅

The proper version released

https://pypi.org/project/promptwatch/0.1.3/

`pip install promptwatch==0.1.3`

Thanks for your cooperation 🙏

**Closed by ju-bezdek** 2023-05-24 14:06 UTC
